(******************************************************************************)
(*                                                                            *)
(*                Fontaine: Ramification Bounds for p-adic Representations    *)
(*                                                                            *)
(*     Formalizes Fontaine's bounds on ramification of p-adic Galois          *)
(*     representations: p-adic fields, local field extensions, higher         *)
(*     ramification groups (upper/lower numbering), Herbrand functions,       *)
(*     Swan conductors, Fontaine period rings (B_HT, B_dR, B_cris, B_st),     *)
(*     filtered φ-modules, admissibility, and Hodge-Tate weights. Proves      *)
(*     crystalline representations have bounded ramification.                 *)
(*                                                                            *)
(*     "Il n'y a pas de représentation p-adique non ramifiée intéressante."   *)
(*     (There is no interesting unramified p-adic representation.)            *)
(*     - Jean-Marc Fontaine                                                   *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 7, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
