(******************************************************************************)
(*                                                                            *)
(*                Fontaine: Ramification Bounds for p-adic Representations    *)
(*                                                                            *)
(*     Formalizes Fontaine's bounds on ramification of p-adic Galois          *)
(*     representations: conductors, Swan conductors, and the relationship     *)
(*     between wild ramification and Hodge-Tate weights. Proves bounds on     *)
(*     ramification breaks for crystalline and semi-stable representations.   *)
(*                                                                            *)
(*     "Il n'y a pas de représentation p-adique non ramifiée intéressante."   *)
(*     (There is no interesting unramified p-adic representation.)            *)
(*     - Jean-Marc Fontaine                                                   *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 7, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
